name: Convert2RMarkdown

on:
  push:
    paths:
      - mkdocs/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Convert to R Markdown
      run: |
        for f in mkdoccs/*.md; do
          echo "move file to" "bookdown/$(basename "$f" .md).rmd"
          cp "$f" "bookdown/$(basename "$f" .md).rmd"
        done